baseURL = 'https://dgmeeyuh.github.io/dgmi/'
languageCode = 'en-us'
theme = "anatole"
title = 'digitally mi'
description = """
Livin'
Lovin'
Disc Golfin'
"""
author = "Mia"
profilePicture = "images/logo.png"
copyright = "{{ YEAR }} Digitally Mi"
showSearch = true
showTags = true
paginate = 5
enableRobotsTXT = true
googleAnalytics = "G-YE37X7B4QB"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:dgmi116281@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/dgmeeyuh"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "linkedin"
url = "https://linkedin.com/in/mialofton"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://instagram.com/dgmi_"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "facebook"
url = "https://facebook.com/dgmi116281"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
name = "Home"
identifier = "home"
url = "/"
weight = 100

[[menu.main]]
name = "Blog"
identifier = "blog"
url = "/blog/"
weight = 200

[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"
weight = 300
