baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'digitally mi'
description = 'Follow my journey in life and disc golf!'
theme = "anatole"

[params]
github = "dgmeeyuh"
linkedin = "mialofton"
instagram = "dgmi_"
facebook = "dgmi116281"